spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local
  jackson:
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: validate
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
  forward-headers-strategy: none

management:
  endpoint:
    health:
      probes:
        enabled: true
