package com.yumg.starter.modules.sqlconsole.application;
import com.yumg.starter.common.api.ApiException; import com.yumg.starter.modules.security.application.AuditService;
import java.sql.ResultSetMetaData; import java.util.*; import org.springframework.core.env.Environment; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service;
@Service public class SqlConsoleService {
 private final JdbcTemplate jdbc; private final AuditService audit; private final boolean localEnabled;
 public SqlConsoleService(JdbcTemplate jdbc, AuditService audit, Environment environment, @org.springframework.beans.factory.annotation.Value("${app.sql-console.enabled:false}") boolean enabled){this.jdbc=jdbc;this.audit=audit;this.localEnabled=enabled&&environment.matchesProfiles("local");}
 public SqlConsoleResult execute(String sql, boolean confirmed){ if(!localEnabled)throw ApiException.notFound(); String statement=validate(sql); boolean query=isQuery(statement); if(!query&&!confirmed)throw ApiException.invalidParameter();
  SqlConsoleResult result=jdbc.execute((java.sql.Connection connection)->{try(var s=connection.createStatement()){s.setMaxRows(100);boolean has=s.execute(statement);if(!has)return new SqlConsoleResult(false,s.getUpdateCount(),List.of());try(var rs=s.getResultSet()){ResultSetMetaData md=rs.getMetaData();List<Map<String,Object>> rows=new ArrayList<>();while(rs.next()){Map<String,Object> row=new LinkedHashMap<>();for(int i=1;i<=md.getColumnCount();i++){String col=md.getColumnLabel(i);Object value=rs.getObject(i);row.put(col, sensitive(col)?"***":value);}rows.add(row);}return new SqlConsoleResult(true,0,rows);}}});
  audit.event("SQL_CONSOLE_EXECUTED","SqlConsole",null,"SUCCESS","{\"kind\":\""+(query?"QUERY":"MUTATION")+"\",\"length\":"+statement.length()+"}");return result; }
 static String validate(String sql){if(sql==null||sql.isBlank()||sql.length()>20000)throw ApiException.invalidParameter();String text=sql.trim();int first=text.indexOf(';');if(first>=0&&first!=text.length()-1)throw ApiException.invalidParameter();return first==text.length()-1?text.substring(0,first).trim():text;}
 private boolean isQuery(String sql){return sql.toLowerCase(Locale.ROOT).matches("^(select|with|explain|pragma)\\b[\\s\\S]*");} private boolean sensitive(String key){String value=key.toLowerCase(Locale.ROOT);return value.contains("password")||value.contains("token")||value.contains("secret")||value.contains("hash");}
}
